spring:
  application:
    name: chasqui-delivery
  profiles:
    active: dev

elasticsearch:
  host: ${ELASTIC_HOST}
  user: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

slash-graph-ql:
  hostname: ${SLASH_GRAPH_QL_HOSTNAME}


server:
  port: 8100
